title: egg berries
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9462366
  brandStrength: 0.1875
  rhythmicContrast: 0.5053763
  brandColors:
    - '#2d2d2d'
    - '#e4e4e4'
    - '#656565'
    - '#a2a2a2'
    - '#828282'
  lightness: 0.4014337
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: egg berries
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.80796
layout_spectrum: 0.4462366
