name: Egg Berries
favicon: null
layout_spectrum: 0.5025
typography_spectrum: 0.9053864891175181
title: The Only Standard For Gentleman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e111a'
    - '#e9e8e3'
    - '#3b4963'
    - '#792600'
    - '#a04f18'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
