name: Egg Berries
favicon: null
layout_spectrum: 0.0006
typography_spectrum: 0.80796
title: The Only Standard For Gentleman
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2d2d'
    - '#e4e4e4'
    - '#656565'
    - '#a2a2a2'
    - '#828282'
  brandStrength: 0.1875
  lightness: 0.4014337
  saturation: 0.9462366
  rhythmicContrast: 0.5053763
purpose: []
