name: eggberries
favicon: null
layout_spectrum: 0.5025
typography_spectrum: 0.9053864891175181
title: The Only Standard For Gentleman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#574545'
    - '#776768'
    - '#eae8e9'
    - '#c7c4bf'
  brandStrength: 0.5
  lightness: 0.6650485515128821
  saturation: 0.6711639941204339
  rhythmicContrast: 0.15875294129364192
purpose: []
